config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => '/sidekiq'
  default_url_options :host => "kulovanshi@bestpeers.com"
  get 'stories/create'
  get 'stories/show'
  get 'stories/new'
  get 'stories/index'
  get 'strories/create'
  get 'strories/show'
  get 'profiles/index'
  get 'images/index'
  
  get 'homes/index'
  root "homes#index"
  get 'users/search', to: "users#search"
  resources :posts do
    post 'like', to: 'likes#like'
    delete 'unlike', to: 'likes#unlike'
  end
  resources :my_profiles
  resources :users
  resources :followers
  resources :profile
  resources :likes
  resources :stories
  resources :comments
  post 'profile/:id/follow', to: 'profile#follow',as: 'follow'
  post 'profile/:id/unfollow', to: 'profile#unfollow', as: 'unfollow'
  post 'profile/:id/accept', to: 'profile#accept', as: 'accept'
  post 'profile/:id/decline', to: 'profile#decline', as: 'decline'
  post 'profile/:id/cancel', to: 'profile#cancel', as: 'cancel'
  post 'profile/:id/block', to: 'profile#block', as: 'block'
  post 'users/sign_in', to: 'devise/sessions#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.like(user, post)
    create(user: user, post: post)
  end

  def self.unlike(user, post)
    like = find_by(user: user, post: post)
    like.destroy if like
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :user_id, uniqueness: {scope: :post_id}

  def self.like(user, post)
    create(user: user, post: post)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :picture
  has_many :likes

  def self.ransackable_attributes(auth_object = nil)
    super + ['username']
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  scope :active, -> { where('expires_at > ?', Time.now) }
  scope :expired, -> { where('expires_at <= ?',Date.end_of_day) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one_attached :image
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :stories
  after_save_commit :welcome_send
  enum role: [:user,:admin]

  followability
  def unfollow(user)
    followerable_relationships.where(followable_id: user.id).destroy_all
  end

  def block(user)
    followerable_relationships.where(followable_id: user.id).blocked
  end

  def welcome_send
    if self.confirmed?
       UserMailer.welcome_email(self).deliver_later
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    super + ['username']
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new 
    @comment = Comment.new 
  end

  def create
    @comment = Comment.create(comment_params) 
    if @comment.save
      @post = @comment.post
      flash[:notice] = "Successfully created"
    else
      flash[:alert] = "Something went wrong ..."
    end
  end
  
  private

  def comment_params
    params.require(:comment).permit(:comment,:user_id,:post_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create 
    @like = current_user.likes.new(like_params)
    if @like.save
      flash[:atert] = "You already liked"
    end
    respond_to do |format|
      format.json { head :no_content }
      format.js   { render :layout => false }
   end
  end

  private
  
  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
    @users = User.all
    @stories = Story.all
    @likes = Like.all
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @post=Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      PostMailer.new_post(@post).deliver_later
      redirect_to controller: :posts, action: :index 
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:add_text, :picture)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
 before_action :set_user

  def show
    @posts = Post.all
  end

  def follow
    current_user.send_follow_request_to(@user)
    redirect_to profile_path(@user),
    notice: 'you have successfully requested'
  end

  def block
    current_user.block(@user)
    redirect_to profile_path(@user)
  end

  def unfollow
    current_user.unfollow(@user)
    redirect_to profile_path(@user)
  end

  def accept
    current_user.accept_follow_request_of(@user)
    make_it_a_friend_request
    redirect_to profile_path
  end

  def decline
    current_user.decline_follow_request_of(@user)
    redirect_to profile_path(@user)
  end

  def cancel
    current_user.remove_follow_request_for(@user)
    redirect_to profile_path(@user)
  end

  def make_it_a_friend_request
    current_user.send_follow_request_to(@user)
    @user.accept_follow_request_of(current_user)
  end

  def make_it_unfriend_request
    @user.unfollow(current_user) if @user.mutual_following_with?(current_user)
  end

  def destroy
    @user.destroy
    redirect_to controller: :users, action: :index, status: :see_other
  end

  private
  
  def set_user
    @user=User.find(params[:id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = current_user.stories.create(story_params)
    if @story.save
      redirect_to posts_path, notice: 'Story created successfully.'
     else 
      flash[:alert] = 'Story could not be created.'
      render :new
    end
  end

  def show
    @story = Story.find(params[:id])
  end

  private

  def story_params
    params.require(:story).permit(:content, :image, :expires_at)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
   @post = Post.all
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @user=User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/my_profiles_helper.rb
module MyProfilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_comment_form.html.erb
<%= form_for [ Comment.new], :html => {:class => "w-50"}, remote: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: post.id %>
  <p class="emoji-picker-container">
  <%= f.text_field :comment, class: "form-control ",data:{emojiable: true}%>
  

  </p>
  <%=f.submit "comment"%>
<% end %>

app/views/posts/index.html.erb
<div class = 'top'> 
  <div class='imgsml'>
    <li>
      <% @stories.each do |story| %>
        <%=image_tag(story.image,size: '100x100',:class=> "img-circular")if story.image.attached? %>   
        <%=link_to "story", story %>
      <%end%>
    <li>
  </div>
</div>
<div class = 'center'>
  <ul>
    <% @posts.each do |post| %>
      <li> 
        <div class="card" style="width: 25rem;">
          <img src="" class="card-img-top">
          <div class ="card-body">
           <%=image_tag post.user.image,size: '100x100',:class=> "img-circular"if post.user.image.attached? %>
           <%=post.user.username%>
            <a href="/posts/<%=post.id %>">
            <%=image_tag post.picture, size: '350x400' %>
            </a>
            <div class="row actions" id="comment-form-post"<%= post.id.to_s %>>
                <%= render 'comment_form', {post: post} %>
            </div>
               <!--for Like section-->
            <div>
            
              <%=button_to 'like', likes_path,params: {like:{post_id: post.id}},method: :post%> 
            
            </div>
            <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
            <%=post.add_text%>
          </div>
        </div> 
      </li> 
    <% end %> 
  </ul>
</div>

<div class="right">
  <div class="card" style="width: 20rem;">
    <img src="" class="card-img-top">
      <div class ="card-body">
      <%=search_form_for @q do |f| %>
   <div class = "form-group">
    <%= f.text_field :username_cont, class: "form-control"%>
    <%=f.submit class:"btn bt-primary btn-lg" %>
    </div>
  <% end %>
        <ul>
        <h5> Suggestion For you</h5>
          <% @users.each do |user| %>
            <li>
              <a href="<%= profile_path(user) %>">
              <%if current_user.following?(user) &&current_user == user%>
              
                <%else %>
                <div class='imgsml'>
                  <%=image_tag(user.image,size: '100x100',:class=> "img-circular")if user.image.attached? %>
                  <%= user.username %>
                </div>
              <%end%>
              </a>
            </li>
          <% end %>
          </ul>
      </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="center">
  <%= form_with model: @post do |form|%>
    <div class="field">
      <%= form.label :picture %><br />
      <%= form.file_field :picture %>
    </div>
    <div class="field">
      <%= form.label :add_text %><br />
      <%= form.text_field :add_text %>
    </div>
    <div class="actions">
      <%= form.submit "Post" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class ="center">
  <div class="card" style="width: 25rem;">
    <img src="" class="card-img-top">
    <h5>Comments</h5>
    <% @post.comments.each do |post| %>
      <div class="card" style="width: 25rem;">
        
        <%=post.user.username%>
        <%= content_with_emoji(post.comment) %>
      </div>
    <%end%>
  </div>
</div>

app/views/stories/create.html.erb
<h1>Stories#create</h1>
<p>Find me in app/views/stories/create.html.erb</p>

app/views/stories/index.html.erb
  <h5>
  <ul>
    <li>You can use these features </li>
   
    <li>follow and friends : you can follow anyone profile and make friends with them</li>
    <li>Stories: CircleConnect Stories allow users to share photos and videos that disappear after 24 hours. </li>
    <li>post: you can upload photos and videos on CircleConnect platform</li>
    <li>Like & Commets: you can Like and commet  on anyone post</li>
    <li>also you can view profile any user on CircleConnect app</li>
  
 </ul>
</h3>

app/views/stories/new.html.erb
  <div class="notice">
<%= form_with(model: @story, url: stories_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :image %><br />
    <%= form.file_field :image %>
  </div>
  <%= form.text_area :content %>
  <%= form.submit 'Create Story' %>
<% end %>
</  div>

app/views/stories/show.html.erb
<div class="center"> 
<%=@story.user.username%>
  <div class="card" style="width: 25rem;">
      <div class ="card-body">
        <div class='imgsml'>
         
          <%=image_tag(@story.image,size: '350x400')if @story.image.attached? %>   
          <p><%= @story.content %></p>  
        </div>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<div class = "center">
  <%=search_form_for @q do |f| %>
   <div class = "form-group">
    <%= f.text_field :username_cont, class: "form-control"%>
    <%=f.submit class:"btn bt-primary btn-lg" %>
    </div>
  <% end %>
  <ul>
    <h5> Users list</h5>
    <% @users.each do |user| %>
      <div class="card" style="width: 20rem;">
        <img src="" class="card-img-top">
        <div class ="card-body">
          <li>
            <a href="<%= profile_path(user) %>">
              <div class='imgsml'>
                <%=image_tag(user.image,size: '100x100',:class=> "img-circular")if user.image.attached? %>
                <%= user.username %>
              </div> 
            </a>
          </li>
        </div>
     </div>
    <% end %>
  </ul>
</div>
<% if current_user %>    
  <%current_user.follow_requests.each do |request|%>
    <%=request.followerable.email%> wants to follow you
    <%=button_to "Accept",accept_path(request.followerable) %>
    <%=button_to "Decline",decline_path(request.followerable) %>
  <%end%>
<%end%>

app/views/users/search.html.erb
<div class = "center">
  <ul>
    <h5> Users list</h5>
    <% @search.each do |user| %>
      <div class="card" style="width: 20rem;">
        <img src="" class="card-img-top">
        <div class ="card-body">
          <li>
            <a href="<%= profile_path(user) %>">
              <div class='imgsml'>
                <%=image_tag(user.image,size: '100x100',:class=> "img-circular")if user.image.attached? %>
                <%= user.username %>
              </div> 
            </a>
          </li>
        </div>
     </div>
    <% end %>
  </ul>
</div>