config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => '/sidekiq'
  default_url_options :host => "kulovanshi@bestpeers.com"
  get 'stories/create'
  get 'stories/show'
  get 'stories/new'
  get 'stories/index'
  get 'strories/create'
  get 'strories/show'
  get 'profiles/index'
  get 'images/index'
  
  get 'homes/index'
  root "homes#index"
  get 'users/search', to: "users#search"
  resources :posts do
    post 'like', to: 'likes#like'
    delete 'unlike', to: 'likes#unlike'
  end
  resources :my_profiles
  resources :users
  resources :followers
  resources :profile
  resources :likes
  resources :stories
  resources :comments
  post 'profile/:id/follow', to: 'profile#follow',as: 'follow'
  post 'profile/:id/unfollow', to: 'profile#unfollow', as: 'unfollow'
  post 'profile/:id/accept', to: 'profile#accept', as: 'accept'
  post 'profile/:id/decline', to: 'profile#decline', as: 'decline'
  post 'profile/:id/cancel', to: 'profile#cancel', as: 'cancel'
  post 'profile/:id/block', to: 'profile#block', as: 'block'
  post 'users/sign_in', to: 'devise/sessions#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.like(user, post)
    create(user: user, post: post)
  end

  def self.unlike(user, post)
    like = find_by(user: user, post: post)
    like.destroy if like
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :user_id, uniqueness: {scope: :post_id}

  def self.like(user, post)
    create(user: user, post: post)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :picture
  has_many :likes

  def self.ransackable_attributes(auth_object = nil)
    super + ['username']
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  scope :active, -> { where('expires_at > ?', Time.now) }
  scope :expired, -> { where('expires_at <= ?',Date.end_of_day) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one_attached :image
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :stories
  after_save_commit :welcome_send
  enum role: [:user,:admin]

  followability
  def unfollow(user)
    followerable_relationships.where(followable_id: user.id).destroy_all
  end

  def block(user)
    followerable_relationships.where(followable_id: user.id).blocked
  end

  def welcome_send
    if self.confirmed?
       UserMailer.welcome_email(self).deliver_later
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    super + ['username']
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create 
    @like = current_user.likes.new(like_params)
    if @like.save
      flash[:atert] = "You already liked"
    end
    respond_to do |format|
      format.json { head :no_content }
      format.js   { render :layout => false }
   end
  end

  private
  
  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
    @users = User.all
    @stories = Story.all
    @likes = Like.all
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @post=Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      PostMailer.new_post(@post).deliver_later
      redirect_to controller: :posts, action: :index 
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:add_text, :picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
   @post = Post.all
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @user=User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/my_profiles_helper.rb
module MyProfilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CircleConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src ="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src ="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar " style="background-color: #87CEFA;"  position= "fixed;">
      <%if user_signed_in?%>
        <div class='imgsml'>
          <%=image_tag( current_user.image,size: '50x50',:class=> "img-circular")if current_user.image.attached? %>
          <%= link_to current_user.username, my_profiles_path, class: "navbar-link"  %>
          <%if current_user.role =="admin" %>
          <%= "admin user"%>
          <%end%>
        </div>
      <%else%>
        <a class="navbar-brand">CircleConnect</a>
      <%end%>
      <form class="form-inline">
        <p class="navbar-text float-left">
        <% if user_signed_in? %>   
        <div class =center>
        <h3><%= CircleConnect%></h3>
        </div>
          <div class = right>
       
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link"  %>
          </div>
         <%else %>
            <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
            <%= link_to "Login", new_user_session_path, class: "navbar-link"  %> 
        <% end %>
        </p>
      </form >
    </nav>
    <%if user_signed_in?%>
   <div class="row">
<div class="col-2">
<nav class ="navbar bg-light">
<ul class ="nav navbar-nav">
<li class ="nav-item">
<a class ="nav-link" href="http://localhost:3000/posts"> Home </a>
</li>
<li class ="nav-item">
<a class ="nav-link" href="http://localhost:3000/users">search </a>
</li>
<li class ="nav-item">
<a class ="nav-link" href="http://localhost:3000/posts/new"> Add post </a>
</li>
<li class ="nav-item">
<a class ="nav-link" href="http://localhost:3000/stories/new"> Story </a>
</li>
<li class ="nav-item">
<a class ="nav-link" href="http://localhost:3000/stories"> About </a>
</li>
</ul>
</nav>
</div>
<%end%>
    <% if notice %> <p class="alert alert-success"><%= notice %></p>
    <% end %> 
    <% if alert %> <p class="alert alert-danger"><%= alert %></p> 
    <% end %>
      <%= yield %>
  </body>
</html>